static constexpr const char* demo_string_lorem_ipsum =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a nisi lacus. Suspendisse et "
    "tellus libero. Sed\n"
    "elementum, quam vitae tempor laoreet, lorem orci pretium ante, nec pulvinar mauris nisl vel "
    "turpis. Nulla gravida\n"
    "mattis neque, sit amet viverra nisi iaculis non. Vivamus at euismod ipsum. Nam posuere "
    "ultricies aliquam. Morbi ac\n"
    "laoreet arcu. Nulla imperdiet faucibus molestie. Donec pretium tincidunt lacus facilisis "
    "aliquet. Fusce quam urna,\n"
    "commodo ut velit non, scelerisque vestibulum risus. Vestibulum convallis urna lacinia lacinia "
    "luctus. Mauris quis\n"
    "venenatis quam. Donec tristique justo sit amet venenatis faucibus. Duis sit amet condimentum "
    "magna.\n"
    "\n"
    "Etiam eu suscipit nulla. Quisque rutrum purus mollis fringilla faucibus. Mauris faucibus, "
    "ante nec pharetra viverra,\n"
    "diam nisi luctus nulla, sed aliquam est justo sed metus. Etiam porttitor dui nec sem pulvinar "
    "mattis. Donec congue\n"
    "turpis sed mi convallis tempus. Maecenas ac lectus porta, dapibus orci sit amet, placerat "
    "lorem. Cras varius lorem ac\n"
    "est auctor sollicitudin eu in risus. Maecenas eget tortor et ligula scelerisque condimentum "
    "vel at purus. Nullam\n"
    "bibendum nunc id purus ullamcorper, eget aliquam metus lacinia. In dolor erat, finibus sit "
    "amet elit ut, luctus\n"
    "mollis tellus.\n"
    "\n"
    "Cras faucibus dolor a porttitor mollis. Sed eget malesuada lacus, vitae vehicula magna. Nunc "
    "cursus ex sed augue\n"
    "tempus vehicula. Ut felis urna, auctor vitae tortor vel, blandit faucibus erat. Ut vehicula, "
    "massa ac efficitur\n"
    "pharetra, turpis tellus porttitor orci, luctus egestas orci nisi tincidunt est. Ut porta eget "
    "sem commodo laoreet.\n"
    "Donec ultrices nunc et tortor bibendum sollicitudin. Maecenas ante lacus, lobortis eu eros "
    "vel, feugiat convallis\n"
    "dolor. Aliquam gravida sollicitudin nisl a posuere. Aenean malesuada in magna sit amet "
    "consectetur. Ut vitae dapibus\n"
    "diam. Vestibulum scelerisque ex non molestie ultrices. Donec tellus diam, rutrum sed egestas "
    "quis, fringilla nec\n"
    "nisi. Nullam vitae tortor a risus gravida lacinia. Integer vel ullamcorper lectus, et pretium "
    "velit. Pellentesque dui\n"
    "ex, maximus et interdum eu, tristique vel nibh.\n"
    "\n"
    "Nulla facilisis nec massa commodo interdum. Curabitur tincidunt nunc odio, a faucibus tellus "
    "tincidunt eget. Ut\n"
    "libero ante, cursus faucibus eros non, ultricies interdum libero. Donec erat nibh, maximus "
    "dignissim urna in,\n"
    "molestie dapibus turpis. Donec tincidunt urna augue, sed molestie metus dictum sit amet. Duis "
    "rhoncus eget nisi eu\n"
    "pellentesque. Nam consequat vel elit in bibendum. Pellentesque vehicula gravida venenatis. "
    "Morbi id dolor sit amet\n"
    "arcu egestas tempus. Morbi imperdiet purus id elit scelerisque dignissim. Pellentesque "
    "finibus feugiat diam, sit amet\n"
    "pretium ante rutrum eget. Etiam porta eleifend euismod. Ut non tincidunt ante, non pharetra "
    "arcu.\n"
    "\n"
    "Aliquam facilisis tristique sollicitudin. Curabitur nisi arcu, fermentum a dui in, venenatis "
    "ullamcorper arcu. Class\n"
    "aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque "
    "mollis nulla id tortor\n"
    "egestas vulputate. Ut dignissim leo non erat tempus tempor. Duis nec hendrerit tortor. Morbi "
    "quam mi, imperdiet at\n"
    "convallis eget, ultricies a metus. Donec et justo dignissim, tristique orci ut, consequat "
    "lorem. Fusce ornare\n"
    "pellentesque turpis at gravida. In hac habitasse platea dictumst. Curabitur quis est eget "
    "eros auctor tempor.\n"
    "\n"
    "Fusce faucibus suscipit nisi, ac pellentesque velit posuere in. Aliquam id ante at nunc "
    "lobortis lobortis eu et nibh.\n"
    "Maecenas elementum ornare varius. Duis risus eros, pretium dictum eleifend at, sagittis vitae "
    "metus. Vestibulum tempor\n"
    "vel enim eget dapibus. Vivamus feugiat felis suscipit tempor scelerisque. Aenean ultrices "
    "massa purus. Cras nulla est,\n"
    "iaculis a nisi non, venenatis ultricies nisi. Nam finibus neque sem, ut gravida tellus tempus "
    "in. Nunc sit amet libero\n"
    "erat. Integer mattis finibus justo vel bibendum. Morbi sit amet dictum nulla.\n"
    "\n"
    "Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum commodo imperdiet "
    "urna, vitae mattis est\n"
    "eleifend efficitur. Maecenas iaculis, enim sit amet mattis elementum, tortor risus "
    "sollicitudin libero, a porta diam\n"
    "nisl in lorem. Duis eget tellus ut nisl malesuada fermentum. Vestibulum ligula elit, pharetra "
    "nec ex nec, mattis\n"
    "dapibus elit. Pellentesque vulputate id erat sit amet congue. Duis condimentum purus sed leo "
    "aliquet efficitur.\n"
    "Vestibulum magna nisi, gravida id vulputate vulputate, facilisis quis ex. Aenean mauris "
    "lacus, condimentum sed felis\n"
    "mollis, eleifend bibendum ipsum. Quisque faucibus urna eget ipsum blandit, nec porta elit "
    "eleifend. Duis nec purus\n"
    "leo.\n"
    "\n"
    "Vestibulum bibendum sem malesuada erat dignissim dictum. Morbi a dolor rhoncus, efficitur "
    "mauris non, tempus magna.\n"
    "Aenean placerat tincidunt est et finibus. Nunc neque libero, aliquet et enim eget, fermentum "
    "gravida dolor. Ut et\n"
    "risus sit amet erat cursus varius quis et arcu. Fusce aliquet urna nec feugiat gravida. Donec "
    "in luctus augue. Nunc\n"
    "consectetur sollicitudin laoreet. Sed placerat feugiat cursus. Proin quis nulla nec odio "
    "iaculis elementum in sed ex.\n"
    "Nullam sed ipsum dictum, efficitur sem eget, viverra felis.\n"
    "\n"
    "Nam non nisi elementum, maximus libero dapibus, malesuada urna. Pellentesque massa orci, "
    "finibus eget risus nec,\n"
    "placerat feugiat arcu. Nam bibendum, tortor vel ultrices bibendum, massa odio convallis orci, "
    "id varius dui lacus sed\n"
    "diam. Cras sit amet laoreet sem, id condimentum enim. Sed a vulputate metus. Vestibulum ipsum "
    "mi, efficitur quis\n"
    "mauris non, scelerisque gravida purus. Curabitur tincidunt condimentum maximus. Quisque "
    "fermentum urna sapien, quis\n"
    "tincidunt leo eleifend ac. Ut non orci magna.\n"
    "\n"
    "Nullam vitae pharetra ex, sed egestas turpis. Donec eu malesuada neque, at porta orci. Fusce "
    "leo metus, lacinia sed\n"
    "consequat aliquam, vulputate at ex. Donec tellus risus, tempus et tristique et, rutrum "
    "fringilla tellus. Etiam\n"
    "interdum volutpat metus, eget mollis ante rutrum a. Nulla facilisi. Duis faucibus turpis "
    "lacus, non ornare nisl luctus\n"
    "vel. Aliquam varius velit at nulla elementum pellentesque. Curabitur in interdum purus. "
    "Curabitur suscipit consectetur\n"
    "malesuada. Morbi rhoncus, diam eu elementum maximus, purus odio auctor libero, in consequat "
    "nunc massa vel nisi. In\n"
    "suscipit sapien at pharetra efficitur. Proin vehicula facilisis porttitor. Interdum et "
    "malesuada fames ac ante ipsum\n"
    "primis in faucibus. Suspendisse orci ipsum, iaculis quis ornare a, tempus nec velit.\n"
    "\n"
    "Curabitur facilisis odio at lectus convallis, eu iaculis massa accumsan. Ut posuere lobortis "
    "justo in dapibus.\n"
    "Curabitur dictum a mauris vel dictum. Quisque efficitur nunc eros, vitae ultrices mauris "
    "volutpat eget. Donec eleifend\n"
    "urna ut interdum condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et "
    "ultrices posuere cubilia curae;\n"
    "Nunc vel suscipit nunc, quis tincidunt felis. Maecenas congue nec sapien nec ultrices. "
    "Phasellus ligula libero,\n"
    "gravida a tortor id, tempor vehicula felis. Aliquam vehicula, quam id cursus tempus, turpis "
    "ex dictum ante, quis\n"
    "ullamcorper mauris quam eget orci. Aenean eget tristique leo. Nullam tristique ultrices velit "
    "et scelerisque.\n"
    "\n"
    "Vestibulum commodo eros sit amet nisi luctus mollis. Donec venenatis urna eu lacus volutpat "
    "auctor. In tempor, justo\n"
    "non interdum fermentum, ipsum ex gravida lorem, vitae auctor nisi lectus vel lorem. Nullam eu "
    "diam in ipsum\n"
    "sollicitudin efficitur nec nec nulla. Cras at velit eget leo interdum luctus nec vitae arcu. "
    "In fermentum rutrum erat\n"
    "et volutpat. Sed dapibus ante enim, non vehicula mauris dictum tempor. Nulla ac tempor quam. "
    "Proin ullamcorper aliquet\n"
    "mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n"
    "\n"
    "Donec sed tempus turpis. Sed nec commodo nibh, sed consectetur orci. Vestibulum semper diam "
    "magna, et efficitur diam\n"
    "scelerisque quis. Quisque non ornare diam. Sed tempor lacinia nisi, tincidunt sollicitudin "
    "massa tincidunt ac.\n"
    "Vivamus erat lorem, auctor at dolor vitae, tincidunt iaculis ex. In hac habitasse platea "
    "dictumst.\n"
    "\n"
    "Donec arcu enim, condimentum nec hendrerit ut, faucibus ut risus. Orci varius natoque "
    "penatibus et magnis dis\n"
    "parturient montes, nascetur ridiculus mus. Etiam ipsum magna, venenatis at accumsan egestas, "
    "cursus a dolor. Aliquam\n"
    "erat volutpat. Nam egestas vestibulum felis sit amet molestie. Nullam mauris libero, blandit "
    "in lacus id, iaculis\n"
    "iaculis libero. Nullam porta magna et nunc hendrerit, a finibus purus pulvinar. Aenean "
    "consectetur quam vitae pulvinar\n"
    "ultrices. Praesent auctor enim at consequat vulputate. Cras placerat semper tempus. Phasellus "
    "auctor orci vitae ligula\n"
    "scelerisque, eget blandit ipsum sagittis. Mauris eu metus sed tortor blandit interdum. "
    "Phasellus varius id quam ac\n"
    "accumsan. Donec ullamcorper, ipsum ut tincidunt efficitur, magna lacus cursus neque, sed "
    "facilisis sem nulla tempor\n"
    "neque. Nunc eu libero sapien. Suspendisse vitae tincidunt turpis.\n"
    "\n"
    "Curabitur imperdiet, diam id posuere facilisis, dui arcu congue dolor, ut dapibus dolor augue "
    "eget turpis. Etiam in\n"
    "felis velit. In sit amet arcu non nisl ultricies semper. Donec ullamcorper ligula orci, sit "
    "amet sagittis eros ornare\n"
    "eu. Proin non facilisis tortor. Vestibulum enim leo, ultricies ac massa a, consectetur "
    "pretium metus. Nam sagittis\n"
    "rhoncus metus quis volutpat. Curabitur quis nulla eget ipsum mollis pretium. Suspendisse "
    "lobortis nunc id accumsan\n"
    "dictum. Fusce efficitur magna eu feugiat venenatis. Duis ac urna diam. Orci varius natoque "
    "penatibus et magnis dis\n"
    "parturient montes, nascetur ridiculus mus. Cras porttitor, odio at maximus pretium, odio "
    "lorem ultricies lectus, sed\n"
    "porta urna mauris quis eros. Vivamus efficitur nec nisl nec ultrices. Etiam pharetra mauris "
    "nunc, quis posuere leo\n"
    "luctus sit amet. Pellentesque quam magna, consectetur id metus vel, mattis lacinia felis.\n"
    "\n"
    "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. "
    "Vestibulum gravida sem\n"
    "mauris, in eleifend neque eleifend eu. Pellentesque at purus volutpat, euismod purus et, "
    "convallis nunc. Nunc\n"
    "malesuada elementum justo non mattis. Aenean pulvinar nibh velit. Aenean dictum venenatis "
    "sem. Integer vel enim arcu.\n"
    "Aliquam dictum dui odio, non tempus neque efficitur in. Donec ac dapibus metus, eget bibendum "
    "magna. In quis nisl\n"
    "convallis, ornare metus in, feugiat mi. Proin id porta orci. Nullam lobortis in velit ut "
    "placerat. Donec consectetur\n"
    "arcu pharetra ligula viverra, vitae placerat est dictum. Aliquam erat volutpat.\n"
    "\n"
    "Sed aliquet, nulla a convallis suscipit, nisl libero fermentum libero, quis vehicula urna "
    "urna ac tortor. Nunc\n"
    "malesuada dapibus euismod. Duis quis porttitor orci, a semper neque. Maecenas in arcu turpis. "
    "Proin elementum\n"
    "tristique arcu et malesuada. Nullam posuere purus vel placerat gravida. Suspendisse egestas "
    "rhoncus auctor. Lorem\n"
    "ipsum dolor sit amet, consectetur adipiscing elit.\n"
    "\n"
    "Nullam pulvinar mauris at nisl rhoncus, vel facilisis urna venenatis. Etiam eu auctor enim, "
    "quis auctor ipsum.\n"
    "Phasellus quis aliquet augue, sit amet imperdiet neque. Vivamus sed porttitor nulla. Fusce "
    "nibh dui, consectetur nec\n"
    "velit at, molestie vestibulum urna. Cras et feugiat elit, at auctor odio. Donec vel mi id "
    "sapien lacinia volutpat id\n"
    "eu ipsum. Fusce aliquet massa nisl, ac posuere quam varius ut. Mauris in sem nisi. "
    "Suspendisse erat sem, molestie eu\n"
    "dui ac, laoreet pellentesque purus. Praesent nisi nisi, faucibus et lorem id, auctor iaculis "
    "arcu. Nulla tortor arcu,\n"
    "congue quis nunc id, vestibulum tincidunt turpis.\n"
    "\n"
    "Donec non ipsum rhoncus, viverra dolor quis, efficitur metus. Aliquam vulputate ultricies "
    "elit. Nunc quis suscipit\n"
    "erat. Ut ac commodo lorem, vitae gravida diam. Etiam scelerisque enim sapien, sed eleifend "
    "sem ultrices ut.\n"
    "Suspendisse eget arcu eget ligula posuere viverra id non lectus. Sed at arcu vel odio "
    "tristique viverra porta\n"
    "vulputate odio. Fusce volutpat at sem et rutrum. Etiam fringilla in eros a feugiat. Aliquam "
    "quis libero sit amet purus\n"
    "congue pharetra id eu neque.\n"
    "\n"
    "Sed vel tellus non ante interdum egestas at at lorem. Etiam in erat pharetra, egestas orci "
    "vel, euismod quam. Morbi\n"
    "eget turpis sed elit mattis consequat. Donec quis mollis tellus. Suspendisse ut augue nec "
    "lacus dignissim imperdiet.\n"
    "Vestibulum luctus vitae metus non consectetur. Aliquam libero lorem, condimentum vel "
    "ultricies et, suscipit eget nunc.\n"
    "Aliquam pretium odio vel nisl vehicula, at venenatis turpis cursus. Curabitur faucibus neque "
    "sed arcu bibendum\n"
    "sagittis. Sed id aliquam nibh, sed molestie eros. Nulla congue molestie venenatis.";

static constexpr const char* demo_string_star_wars = "War! The Republic is crumbling\n"
                                                     "under attacks by the ruthless\n"
                                                     "Sith Lord, Count Dooku.\n"
                                                     "There are heroes on both sides.\n"
                                                     "Evil is everywhere.\n"
                                                     "\n"
                                                     "In a stunning move, the\n"
                                                     "fiendish droid leader, General\n"
                                                     "Grievous, has swept into the\n"
                                                     "Republic capital and kidnapped\n"
                                                     "Chancellor Palpatine, leader of\n"
                                                     "the Galactic Senate.\n"
                                                     "\n"
                                                     "As the Separatist Droid Army\n"
                                                     "attempts to flee the besieged\n"
                                                     "capital with their valuable\n"
                                                     "hostage, two Jedi Knights lead a\n"
                                                     "desperate mission to rescue the\n"
                                                     "captive Chancellor....";
